### ISSUE TITLE
Does this support multi-level key-values in resource file?

### ISSUE THREAD

**Issue by wuzinong** [alibaba/react-intl-universal#105]
Dear , 
During the usage of this library I meet a problem, when I try to define a structure in resource file like
{
  "HOME":{
      “About_Text”:"About me"
   }，
  "SIMPLE": "Simple Sentence",
}
And then try to use intl.get('HOME').get('About_Text') and it throw an error. 
Is there anywhere that I can find the detailed document which may guide me on that or other similar questions? THX

**Comment by cwtuan** [comment]
Yes, try `intl.get('HOME.About_Text')`
