### ISSUE TITLE
i18n pseudo-localization made easy

### ISSUE THREAD

**Issue by ceszare** [alibaba/react-intl-universal#106]
Hi!

First of all, thank you so much for this library. I am using it successfully in my projects, and it is great!

Secondly, I created a utility that allows me to use pseudo-localization on my configs. I named it [react-intl-universal-pseudo-converter](https://github.com/ceszare/react-intl-universal-pseudo-converter) as it uses the JSON format you provided.

If you would like to and feel it is useful to other users in your library, feel free to link it in your documentation.

Thanks!

**Comment by ceszare** [comment]
They are mostly used for testing locales and not for real translations. When working on internal builds, they help you identify strings that have been localized, versus ones that haven't. It also allows you to have a language to switch to from the beginning if you don't already have translation files ready for other languages.

Here is a bit more information for them:

https://docs.microsoft.com/en-us/windows/desktop/intl/pseudo-locales

https://en.wikipedia.org/wiki/Pseudolocalization

**Comment by cwtuan** [comment]
Thanks for the contribution. README updated.
