### ISSUE TITLE
Questions: Is there a way to avoid waring: A message must be provided as a String or AST

### ISSUE THREAD

**Issue by yuenmadmad** [alibaba/react-intl-universal#107]
Hello, I was trying to get language data which is an array and try to loop these data into multiple custom react components. It works but have warning message: **A message must be provided as a String or AST**. How can I get rid of this message OR I can do this by an alternative way. Please inspire me. = =

Thank you!

**Comment by cwtuan** [comment]
Please show me an example reproducing  the warning.

**Comment by yuenmadmad** [comment]
@cwtuan 
[example](https://github.com/yuenmadmad/reproduce-react-intl-universal-warning) just created.
Not sure if it can be wrote like this, works but have warnings
```
// App.js
Object.keys(intl.get('common')).map(happy => <div>{happy}</div>)
```

**Comment by cwtuan** [comment]
Should just use `intl.get('common.happy1')`. Why do you need to loop that?

**Comment by yuenmadmad** [comment]
```json
{
  "cards": [ 
     {
        "title": "title with diff languages1",
        "imgUrl": "blablabal1.png"
     },
     {
        "title": "title with diff languages2",
        "imgUrl": "blablabal2.png"
     }
  ]
}
```
Case like slider shd to loop
