### ISSUE TITLE
复数问题

### ISSUE THREAD

**Issue by FrendEr** [alibaba/react-intl-universal#109]
`"PHOTO": "You have {photoNum, plural, =0 {no photos.} =1 {one photo.} other {# photos.}}"`

上面是复数在demo里面的例子，我本地运行是好的。
但是在我的项目中使用了 `other` 就会报错了，会提示整个 en_US 语言包加载失败。

请问这个有问题有遇到过吗？求指导

**Comment by cwtuan** [comment]
Show me the code and error message.

**Comment by cwtuan** [comment]
Closing issue because of no response.
