### ISSUE TITLE
when the browser lt ie11,it tips that "react-intl-universal format message failed for key='COUPON'. “Intl”未定义"

### ISSUE THREAD

**Issue by dragoncl** [alibaba/react-intl-universal#112]
![image](https://user-images.githubusercontent.com/16948494/54251142-50c9a200-4581-11e9-9fcc-a5c5b84ef358.png)

**Comment by dragoncl** [comment]
I resolve it when i use it in index.js
import 'intl';
import 'intl/locale-data/jsonp/en';

**Comment by cwtuan** [comment]
Did you visit the demo site? I have't encountered this issue in IE11.

**Comment by cwtuan** [comment]
I have tested it in the [demo site](https://g.alicdn.com/alishu/common/0.0.95/intl-example/index.html), it works fine.
![image](https://user-images.githubusercontent.com/3455798/55210216-50880280-5221-11e9-9074-b1a3165e5b77.png)
