### ISSUE TITLE
Not working for MESSAGE_NOT_IN_COMPONENT 

### ISSUE THREAD

**Issue by le0zh** [alibaba/react-intl-universal#113]
Based on the [MessageNotInComponent](https://github.com/alibaba/react-intl-universal/blob/55f485eb5e/examples/browser-example/src/MessageNotInComponent.js#L9)  example, the following codes are not woking as expected. 

```
import React, { Component } from 'react';
import util from './util';

const message = util.getMessage(); // Here will always get default or empty string!

class MessageNotInComponent extends Component {
  render() {
    return (
      <div>
        <div className="title">Message Not in Component Example:</div>
        <div>{message}</div>
      </div>
    );
  }
}

export default MessageNotInComponent;
```

The `message` will always be default or empty string!

**Comment by cwtuan** [comment]
Since your `util.getMessage()`  is executed out of class, the `message` is determined when JS loaded. So, you need to put `util.getMessage()` in the function.

```
import React, { Component } from 'react';
import util from './util';

class MessageNotInComponent extends Component {
  render() {
    const message = util.getMessage()
    return (
      <div>
        <div className="title">Message Not in Component Example:</div>
        <div>{message}</div>
      </div>
    );
  }
}

export default MessageNotInComponent;
```

**Comment by cwtuan** [comment]
By the way, if you want to leave the message outside of function, you could lazy import the file. The lazy imported file is executed after `intl.init`, so the message will work as expected.
