### ISSUE TITLE
Support partial singleton in react-intl-universal

### ISSUE THREAD

**Issue by d9767192** [alibaba/react-intl-universal#115]
Hi, folks. I have a suggestion about react-intl-universal. Could we separate instance of ReactIntlUniversal into another file? In my case, I need to instance a partial singleton in sub-project so that I would have many intl instances in my whole project.
Although I could separate it manually by installing intl in each sub-project, it's ugly for me.
Furthermore, I think separate instance and class would have high extensibility if you want to enhance intl by yourself or something what...
Please think about this suggestion. If it's a great suggestion, I can PR the codes. Thanks.

**Comment by cwtuan** [comment]
Released in v1.16.1
