### ISSUE TITLE
MAJOR ISSUE IE11 + Edge <= 16

### ISSUE THREAD

**Issue by OZZlE** [alibaba/react-intl-universal#117]
This module uses `console.warn()` like this for Strings that aren't translated

    react-intl-universal key "Shortcut links" not defined in en-en_US

In IE11 + Edge <= 16 console is not defined **unless** you have developer tools opened.. so this crashes the entire site.

**Comment by OZZlE** [comment]
See: https://stackoverflow.com/questions/31685216/site-behaves-differently-when-developer-tools-are-open-ie11

**Comment by cwtuan** [comment]
`console-polyfill` is used in this library, it shouldn't have this issue. 
Could you provide an example in codesanbox that makes it failed in IE11?

**Comment by OZZlE** [comment]
Well it's like impossible to debug since I can't open developer tools (because then it works)..

But I assume it must be some method which it doesn't fixes like `console.table` ?  https://github.com/paulmillr/console-polyfill/issues/4

I guess it's more related to an issue in console-polyfull.. sorry I missed that you were using that..

**Comment by cwtuan** [comment]
Only `console.warn` is used in this library. 
Please provide a example for this issue.

**Comment by cwtuan** [comment]
![image](https://user-images.githubusercontent.com/3455798/58238263-8953dc00-7d79-11e9-926d-657943f34bb2.png)

I have tested if console.warn breaks IE 11/ IE 10, it works fine.
