### ISSUE TITLE
如何根据redux状态变化初始化locale

### ISSUE THREAD

**Issue by Chris0316** [alibaba/react-intl-universal#121]
我可以在react根组件app.js中通过事件实时无刷新初始化语言包。但是当我把状态加到redux中时，当前语言切换后无法自动初始化语言包。 如果在根组件渲染方法中调用loadLocales就会陷入死循环使浏览器崩溃。

**Comment by cwtuan** [comment]
`load` will not trigger component rendering, it just merge the locale file to internal object. So, your deadlock problem is not related to `react-intl-universal`.

**Comment by Chris0316** [comment]
Could you please guide how to re-initialize the locale depends on a redux state? Because I can only initialize the locale once in the componenetDidMount hook. When the redux state change, the intl.inti will not be called.

**Comment by DongShi** [comment]
@Chris0316 try use some other way out of component lifecycle methods.
One option is to use event trigger, maybe [event-emitter](https://github.com/medikoo/event-emitter#readme) could help?
First let your root component subscribe some event like 'LOCALE_CHANGE', and in root's render, make locale a key. 

```javascript
// componentDidMount
intl.init(defaultLocale)
eventEmitter.on('LOCALE_CHANGE', this.changeLocale)

// componentWillUnmount
eventEmitter.off('LOCALE_CHANGE', this.changeLocale)

// changeLocale
this.changeLocale = locale => intl.init(locale)

// in render
render () {
   return <div key={store.getStatus().locale}> {xxx}</div> 
}

// in redux reducer

case 'SWITCH_LOCALE_ACTION' {
   state.locale = payload.locale
   eventEmitter.emit('LOCALE_CHANGE', state.locale)
}

```


So when your locale related store state changes, the state would emit a global event, and your root component should re-init locale and re-render accordingly.

**Comment by Chris0316** [comment]
Thanks for the replies, finally I have to use event to change the current language without refresh the page.
