### ISSUE TITLE
How to use multiple react-intl-universal instance? Add merge support?

### ISSUE THREAD

**Issue by DongShi** [alibaba/react-intl-universal#122]
We are working on a multiple page react App, where each page has its own i18n messages bundles and each page is rendered sepratedly with ReactDOM.render().

So we want to each page has its own react-intl-universal instance to handle the i18n affair.
However, seen from the implementation of your [index.js](https://github.com/alibaba/react-intl-universal/blob/master/src/index.js), a singleton instance is exported, no?

Another thought is to provide an intl.merge API along with [intl.init](https://github.com/alibaba/react-intl-universal/blob/4f966f292e0314ee12bb00b8c66fbef7fcf548af/src/ReactIntlUniversal.js#L164), which allow user to add messegs dynamically.

You may argue that we can merge all the messages for all the pages manually, but this is not optimal, we want to speed up our initial loading and rendering,  we do not want a large message bundle at the very beginning which might impact the performance.

**Comment by cwtuan** [comment]
`react-intl-universal` is singleton by default. However, you could instantiate it on demand. 

```
import { ReactIntlUniversal } from 'react-intl-universal';
const intl = new ReactIntlUniversal();
```

**Comment by DongShi** [comment]
Hi @cwtuan 
Does this actually work? I tried in my client code, and get undefined for ReactIntlUniversal?

![image](https://user-images.githubusercontent.com/5009987/66619818-de9d6680-ec10-11e9-8a52-668ff2ee0796.png)

What I can do is to create another instance via

> const newIntl = intl.__proto__.constructor()


but this looks too hacky.

**Comment by cwtuan** [comment]
@DongShi do you use the last version?

**Comment by DongShi** [comment]
hi @cwtuan 
I am using version 2.0.3 which has the same index file as you pointed.
I am using it in a pure browser-side react app.

**Comment by cwtuan** [comment]
@DongShi please try v2.2.1.
