### ISSUE TITLE
讨论一下，关于错误信息，后端只返回错误编码，前端去做国际化，这样合适吗？

### ISSUE THREAD

**Issue by theprimone** [alibaba/react-intl-universal#123]
后台管理系统拦截响应后如果有错，就 `switch` 错误码，再调用相关的国际化配置。

如果还有安卓和 iOS 的客户端时，都得对错误做国际化，虽然后台和客户端可能调用接口存在差异，但是这样每个端都对错误码做一套国际化是不是成本太高了？

如果带上终端的语言，让后台直接返回对应的错误信息，终端只需要打印出来是不是一个更好的选择呢？

**Comment by cwtuan** [comment]
In our team, the request i18n is done in the backend. 
Otherwise, the locales file need contains all of the possible error message. The file may be too large.
