### ISSUE TITLE
不能获取到对应的键值

### ISSUE THREAD

**Issue by icantunderstand** [alibaba/react-intl-universal#124]
try {
      return intl.get(key, params).d(d || key)
    } catch (err) {
      console.log('ingetCatch', key)
      return d || key
    }
locals
{ aa: "aaa {  sdsds }" }

intl.get('aa')  期待返回 aaa{sdsds}

实际 返回  aa

**Comment by cwtuan** [comment]
Do you `init(...)` intl before `get(...)` locale?

**Comment by icantunderstand** [comment]
i have inited    other value like 'aaaa' 'bbb' work fine . but value like '{aaa}111' does not work well.

**Comment by cwtuan** [comment]
Try
```
intl.get('aa', { sdsds:123 })
```

And locale file:
```
{ aa: "aaa {sdsds}" } => without space between "{" and "}"
```
