### ISSUE TITLE
cdn 不稳定

### ISSUE THREAD

**Issue by ubuntugx** [alibaba/react-intl-universal#125]
cdn这周内出现了两次连接超时的情况，导致我们的平台不能使用了https://g.alicdn.com/react-intl-universal/locale-data/1.0.0/zh.js

**Comment by ubuntugx** [comment]
目前的版本好像不支持 cdn 地址自己配置了 https://github.com/alibaba/react-intl-universal/issues/71，还有其他方式可以实现么

**Comment by cwtuan** [comment]
Upgrade to ^2.0.3 and require the locale file in your app.
FYI: https://github.com/alibaba/react-intl-universal/releases/tag/2.0.3
