### ISSUE TITLE
react production build fails when console is stripped

### ISSUE THREAD

**Issue by ahaus** [alibaba/react-intl-universal#126]
I created a react app with create-react-app. 

For production builds i am removing console messages using changes in the webpack configuration.
See: https://stackoverflow.com/questions/56276325/how-can-remove-console-log-in-the-production-build-of-a-react-application-create

The build fails to load because the option warningHandler is not defined.

I suggest to define this option as a function instead to binding it directly to console.

I changed (line 75 in lib/index.js or line 21 in ReactIntlUniversal.js)
`warningHandler: console.warn.bind(console),`
to
`warningHandler: function warn(msg) {console.warn(msg)},`

This solved the issue for me.

**Comment by cwtuan** [comment]
fixed in v2.2.3
