### ISSUE TITLE
Being able to call API outside of React component and function

### ISSUE THREAD

**Issue by MASIROU** [alibaba/react-intl-universal#127]
I want to be able to call the Intl API outside of the React Component like the following. I also have a message file where you define messages for each js file for the better structure like the following. 

example.js
```
import intl from 'react-intl-universal'
import  { messages } from './messages'

const someToggle = [
　　　 { label: intl.formatMessage(messages.hello), value: false },
             { label: intl.formatMessage(messages.hello2), value: true },
 ]

return ( 

// use someToggle in the here

)
```

messages.ts 
```
export const messages = {
    hello: {
        id: 'test'
        defaultMessage: 'Hey',
    },
} as const
```

But as mentioned here https://github.com/alibaba/react-intl-universal/issues/113, calling intl function outside of React component will cause us to get a default message. Is there any way to achieve this structure? Is using lazy import the only way to solve this?

I thought one of the biggest advantages over the react-intl is being able to call intl API outside of React component (although they technically can now) so i'm confused about this issue. 

Thank you for your help in advance.

**Comment by cwtuan** [comment]
One simple way to use Intl API outside of the React Component is make your message as a function.
```jsx
const someToggle = () => [
　{ label: intl.formatMessage(messages.hello), value: false },
   { label: intl.formatMessage(messages.hello2), value: true },
 ]

class Foo extends Component{
 render() {
   return someToggle()[0].label
 }
}
```

**Comment by MASIROU** [comment]
So there is no way to execute "intl.init" before loading these constants? preferably, I do not want to make these constants a function. Thank you!

**Comment by cwtuan** [comment]
Make the locale file loaded before your app js loaded.
For example, 
```
<html>

<head>
   <script>
        window.locales = {enUS:  {...}}
   </script>
   <script src="index.js" />
</head>
</html>
```

**Comment by MOKO2525** [comment]
how come loading locale file first helps in this case?

**Comment by cwtuan** [comment]
@MOKO2525 
The `locales` is just an object, so you could use it in js:
```
import intl from 'react-intl-universal';
intl.init({
  locales: windows.locales,
  // other options..
})
```

**Comment by MOKO2525** [comment]
sorry i'm confused how to load a locale file before app loads in scripts tag like below

```
<html>

<head>
   <script>
      window.locales = { enUS:  {...} }
   </script>
   <script src="index.js" />
</head>
</html>
```

**Comment by cwtuan** [comment]
@MOKO2525 
Is your locales file in the backend server or CDN?
The example above is rendering locales data in html in backend.

**Comment by cwtuan** [comment]
Another solution is using lazy load for the components. 
The components could be loaded after `intl.init` in this case.
Please check: https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by MOKO2525** [comment]
I'm storing the local JSON files for locale.

**Comment by MOKO2525** [comment]
I was looking at the source code of intl.init and found a comment . 

      // init() will not load external common locale data anymore.
      // But, it still return a Promise for abckward compatibility.

If I'm loading the locale json file locally, does it mean we can call intl.init like a sync function without any problem?

**Comment by cwtuan** [comment]
Just load the locale data before `init()`.
Using lazy loading in react-route can solve this issue.
