### ISSUE TITLE
Simplify the process of changing locale?

### ISSUE THREAD

**Issue by MASIROU** [alibaba/react-intl-universal#128]
I want users to be able to change the language, and I simply did the following, and it seems to be working fine. 

```
intl.options.currentLocale = (language chosen by the user).
```

Is this the recommended way to change the locale for intl object? I thought I had to re-initialize with the function "intl" with the new locale. 

If this is not the recommended way to change the locale, It would be great if we had a better way to change locale of intl object rather than re-initializing it.

**Comment by cwtuan** [comment]
```
const options = intl.getInitOptions();
options.currentLocale = 'xxx';
initl.init(options)
```

**Comment by MOKO2525** [comment]
Thank you for the reply. Do you see any disadvantage of using the following way?

```
intl.options.currentLocale = (language chosen by the user).
```

**Comment by cwtuan** [comment]
@MOKO2525 
Yes, you could just write 
```
intl.options.currentLocale = (language chosen by the user).
```
