### ISSUE TITLE
当我的项目引入redux之后，更改语言组件内部不自动刷新

### ISSUE THREAD

**Issue by jthug** [alibaba/react-intl-universal#129]
我的index.js
`ReactDOM.render(<Provider store={store}>
    <MyRouter />
</Provider>, document.getElementById('root'));`
主容器
`import React from "react";
import styles from "./Admin.module.scss";
import bg from "../resource/bg.mp4";
import ic_nest_logo from "../resource/ic_nest_logo.png";
import cs from "classnames";
import Home from "./home";
import Understand from "./understand";
import JoinNest from "./JoinNest";
import Relative from "./Relative";
import Cooperation from "./Cooperation";
import intl from "react-intl-universal";
import { Menu, Dropdown } from "antd";
import "antd/dist/antd.css";
import * as Actions from "../redux/Actions";
import { connect } from "react-redux";
import ic_menu from "../resource/ic_menu.png";
import ic_close from "../resource/ic_close.png";
const locales = {
  en_US: require("../language/en_US.json"),
  zh_CN: require("../language/zh_CN.json"),
};

class Admin extends React.Component {
  componentDidMount() {
    this.loadLocales();
  }

  state = {
    initDone: false,
    currentLanguage: "zh_CN",
    openMenu: false,
  };

  loadLocales(language = "zh_CN") {
    intl
      .init({
        currentLocale: language,
        locales,
      })
      .then(() => {
        this.setState({
          initDone: true,
          currentLanguage: language,
        });
      });
  }

  switchMenu() {
    this.setState({
      openMenu: !this.state.openMenu,
    });
  }

  navigateTo(target) {
    if (target) {
      let element = document.getElementById(target);
      if (element) {
        element.scrollIntoView({ behavior: "smooth" });
      }

      this.props.switchCurrentPage(target);
      this.setState({
        openMenu: false,
      });
    }
  }

  currentTitle(){
    switch(this.props.currentPage){
      case "0":
        return "HOME"
       case "1":
       return intl.get("about_nest")
       case "2":
       return intl.get("join_nest")
       case "3":
       return intl.get("products")
       case "4":
       return intl.get("cooperation")
       default:
        return "hahaah"
    }
  }

  /**
   * 鼠标滑动
   * @param {*} e
   */
  onMouseWheel(event) {
    let scrollY = event.deltaY;
    // console.log("xxx：距离"+scrollY)
  }

  /**
   * 
   * @param {*} event 
   */
  onMove(event){
    // console.log("xxx onMove")
  }

  menu = (
    <Menu>
      <Menu.Item>
        <div
          onClick={() => {
            this.loadLocales("zh_CN");
          }}
        >
          中文
        </div>
      </Menu.Item>
      <Menu.Item>
        <div
          onClick={() => {
            this.loadLocales("en_US");
          }}
        >
          English
        </div>
      </Menu.Item>
    </Menu>
  );

  render() {
    return (
      this.state.initDone && (
        <div className={styles.admin}>
          <video src={bg} loop="loop" autoPlay="autoplay" muted="muted" />

          <div className={styles.columnWrap}>
            <div className={styles.topColumn}>
              <div
                className={cs(styles.topColumnItem, {
                  [styles.topAnim1]: true,
                })}
              />
              <div
                className={cs(styles.topColumnItem, {
                  [styles.topAnim2]: true,
                })}
              />
              <div
                className={cs(styles.topColumnItem, {
                  [styles.topAnim3]: true,
                })}
              />
              <div
                className={cs(styles.topColumnItem, {
                  [styles.topAnim4]: true,
                })}
              />
              <div
                className={cs(styles.topColumnItem, {
                  [styles.topAnim5]: true,
                })}
              />
              <div
                className={cs(styles.topColumnItem, {
                  [styles.topAnim6]: true,
                })}
              />
            </div>

            <div className={styles.bottomColumn}>
              <div
                className={cs(styles.bottomColumnItem, {
                  [styles.bottomAnim1]: true,
                })}
              />
              <div
                className={cs(styles.bottomColumnItem, {
                  [styles.bottomAnim2]: true,
                })}
              />
              <div
                className={cs(styles.bottomColumnItem, {
                  [styles.bottomAnim3]: true,
                })}
              />
              <div
                className={cs(styles.bottomColumnItem, {
                  [styles.bottomAnim4]: true,
                })}
              />
              <div
                className={cs(styles.bottomColumnItem, {
                  [styles.bottomAnim5]: true,
                })}
              />
              <div
                className={cs(styles.bottomColumnItem, {
                  [styles.bottomAnim6]: true,
                })}
              />
            </div>
          </div>
          <div
            style={{
              position: "fixed",
              width: "100%",
              height: "100%",
              backgroundColor: "#f5f7fa",
              zIndex: "-11",
            }}
          />
          <div className={styles.lefRingWrap}>
            <div className={styles.outerRing}>
              <div className={styles.innerRing} />
            </div>
          </div>

          <div className={styles.rightRingWrap}>
            <div className={styles.outerRing}>
              <div className={styles.innerRing} />
            </div>
          </div>
          <div className={styles.head}>
            <img className={styles.logo} src={ic_nest_logo} alt="" />

            <div
              className={cs(styles.navigator, {
                [styles.openMenu]: this.state.openMenu,
              })}
            >
              <div
                className={cs(styles.menuItem, {
                  [styles.memuSelect]: this.props.currentPage === "0",
                })}
                onClick={this.navigateTo.bind(this, "0")}
              >
                HOME
              </div>
              <div
                className={cs(styles.menuItem, {
                  [styles.memuSelect]: this.props.currentPage === "1",
                })}
                onClick={this.navigateTo.bind(this, "1")}
              >
                {intl.get("about_nest")}
              </div>
              <div
                className={cs(styles.menuItem, {
                  [styles.memuSelect]: this.props.currentPage === "2",
                })}
                onClick={this.navigateTo.bind(this, "2")}
              >
                {intl.get("join_nest")}
              </div>
              <div
                className={cs(styles.menuItem, {
                  [styles.memuSelect]: this.props.currentPage === "3",
                })}
                onClick={this.navigateTo.bind(this, "3")}
              >
                {intl.get("products")}
              </div>
              <div
                className={cs(styles.menuItem, {
                  [styles.memuSelect]: this.props.currentPage === "4",
                })}
                onClick={this.navigateTo.bind(this, "4")}
              >
                {intl.get("cooperation")}
              </div>
            </div>
              <div className={styles.headTitle}>{
                this.currentTitle()
              }</div>
            <div className={styles.headRight}>
            <Dropdown overlay={this.menu}>
              <div className={styles.language}>
                <span
                  className={cs(styles.languageType, {
                    [styles.languageSelect]:
                      this.state.currentLanguage === "zh_CN",
                  })}
                >
                  CN
                </span>
                /
                <span
                  className={cs(styles.languageType, {
                    [styles.languageSelect]:
                      this.state.currentLanguage === "en_US",
                  })}
                >
                  EN
                </span>
              </div>
            </Dropdown>
            <img
              className={styles.menuVisiable}
              src={this.state.openMenu ? ic_close : ic_menu}
              alt=""
              onClick={this.switchMenu.bind(this)}
            />
            </div>
            
          </div>

          <div
            className={styles.content}
            onWheel={this.onMouseWheel.bind(this)}
            onTouchMove={this.onMove.bind(this)}
          >
            <div id="0" className={styles.page}>
              <Home
                nextPage={this.navigateTo}
                currentPage={this.state.currentPage}
              />
            </div>
            <div id="1" className={styles.page}>
              <Understand currentPage={this.state.currentPage} />
            </div>
            <div id="2" className={styles.page}>
              <JoinNest currentPage={this.state.currentPage} />
            </div>
            <div id="3" className={styles.page}>
              <Relative currentPage={this.state.currentPage} />
            </div>
            <div id="4" className={styles.page}>
              <Cooperation currentPage={this.state.currentPage} />
            </div>
          </div>
        </div>
      )
    );
  }
}

const mapStateToProps = (state) => {
  return {
    currentPage: state.currentPage,
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    switchCurrentPage: (page) => {
      dispatch(Actions.switchCurrentPage(page));
    },
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(Admin);
`

**Comment by cwtuan** [comment]
Please provide a https://jsfiddle.net/ case.
