### ISSUE TITLE
typing没有暴露ReactIntlUniversal构造函数

### ISSUE THREAD

**Issue by supergaojian** [alibaba/react-intl-universal#131]
在ts开发中使用`import { ReactIntlUniversal } from 'react-intl-universal';` 会报错：
`Module '"react-intl-universal"' has no exported member 'ReactIntlUniversal'.`
但是lib中确实暴露了`ReactIntlUniversal`方法且可使用

**Comment by cwtuan** [comment]
```
import * as intl from 'react-intl-universal'; 
```
