### ISSUE TITLE
react-intl-universal locales data "null" not exists.

### ISSUE THREAD

**Issue by gitfornncn** [alibaba/react-intl-universal#133]
加载语言文本时，会出现react-intl-universal locales data "null" not exists.这样的报错，但实际是有加载到。想了解下是什么原因呢
 <span>{intl.get("public.title")}</span>

**Comment by callmejm** [comment]
一样有相同问题

**Comment by cwtuan** [comment]
Do you `intl.init` before render your app?

**Comment by Chevindu** [comment]
I am having the same warning in my console. I do `intl.init()` in my `componentDidMount()` method. No visible issues with loading strings, though.

![react-intl-universal locales data "null" not exists](https://user-images.githubusercontent.com/11093698/87004970-ea3baf00-c1db-11ea-9e57-f52f84da675c.png)

**Comment by cwtuan** [comment]
Do you intl.init before render your app?
Check the example:
https://github.com/alibaba/react-intl-universal/blob/master/examples/browser-example/src/App.js#L55

**Comment by cwtuan** [comment]
See the solution: https://github.com/alibaba/react-intl-universal/issues/144#issuecomment-1345193138
