### ISSUE TITLE
Update README [Vanilla JS]

### ISSUE THREAD

**Issue by dopt** [alibaba/react-intl-universal#143]
Hi, I just tested that the react-intl cannot be used in Vanilla JS, but the README seems to be confusing because it mentioned that _Can be used not only in React.Component but also in Vanilla JS._

Therefore, I suggest to update the README to prevent confusion.

![image](https://user-images.githubusercontent.com/2612333/94399061-47228200-0199-11eb-99c5-97101bfb424f.png)

**Comment by cwtuan** [comment]
react-intl cannot be used in Vanilla JS, but react-intl-universal can make it.

**Comment by dopt** [comment]
my bad, yes indeed it can.
