### ISSUE TITLE
react-intl-universal locales data "null" not exists.

### ISSUE THREAD

**Issue by Bingjiajia** [alibaba/react-intl-universal#144]
when only use react is ok, but when use redux connect()(MyComponent) with the warning and no result. 

`class MyComponent extend react.Component{
  render(){
    return <h1>{intl.get('string')}</h1>
  }
}`

**Comment by cwtuan** [comment]
do you `init` before `render`?

**Comment by Bingjiajia** [comment]
### i have do in in  **index.js**  
`loadLocales = (lang = 'zh-CN') => {
    intl.init({
      currentLocale: lang,
      locales,
    }).then(() => {
      this.setState({
        antdLang: lang === 'zh-CN' ? zh_CN : en_US
      })
    })
  };

  render() {
    return (
      <Provider store={store}>
        <ConfigProvider locale={this.state.antdLang}>
          <Router>
            <Routers/>
          </Router>
        </ConfigProvider>
      </Provider>
    )
  }`

### then i use it in <Router><MyComponent /></Router>

**<MyComponent /> i use redux connect(MyComponent) i don't init intl in MyComponent again**

**Comment by cwtuan** [comment]
Use debugger to make sure you `init` before `render`

**Comment by dahuotu** [comment]
我也遇到同样的问题，在WEB浏览器中使用没有这个问题，但是打包成谷歌浏览器插件就报这个错误。一度怀疑是我的WEB3应用导致的，注释后问题依旧。

**Comment by dahuotu** [comment]
出现这个问题一般是应用本地语言包路径错误导致的

**Comment by dahuotu** [comment]
出现这个问题一般是应用本地语言包路径错误导致的

**Comment by cwtuan** [comment]
@dahuotu 
so, is the locale file `null` in your web3 app due to location issue?

**Comment by dahuotu** [comment]
@cwtuan 是的，最后在每个调用组件都引用locale文件路径就正常了。

**Comment by Daviontheone** [comment]
For anyone that is still experiencing this warning. For me it was because some data objects were in the root of the file

So this will throw a warning:
`const object = {  displayText: intl.get('KEY').d('Example text') }`

And this won't
`const exampleFunction = () => {
  const object = {  displayText: intl.get('KEY').d('Example text') }
}`





[3:52](https://rktlb.slack.com/archives/D04CNL9HYL8/p1670561558901879)
i.e. all intl.get() calls need to be within a function

**Comment by cwtuan** [comment]
Yes, you should call `intl.init` before `render`.

For example, if you have some constants like this:
```jsx
// Wrong: the message in constants.fruits is used before `intl.init(...)`
const constants = {
    fruits : [
        { label: intl.get('banana'), value: 'banana' },
        { label: intl.get('apple'), value: 'apple' },
    ]
}
function MyComponent() {
    return <Select dataSource={constants.fruits} />
}
```

## Solution 1
Make the message object as a function, and call it at render function

```jsx
const constants = {
    fruits : () => [  // as a function
        { label: intl.get('banana'), value: 'banana' },
        { label: intl.get('apple'), value: 'apple' },
    ]
}
function MyComponent() {
    // fruits is a function which returns message when rendering
    return <Select dataSource={constants.fruits()} />
}
```

## Solution 2
Use [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) syntax to make a function  call when that property is looked up

```jsx
const constants = {
  fruits: [
    {
      get label() {
        return intl.get("banana");
      },
      value: "banana",
    },
    {
      get label() {
        return intl.get("apple");
      },
      value: "apple",
    },
  ],
};
function MyComponent() {
  // When "label" property is looked up, it actually make a function call 
  return <Select dataSource={constants.fruits} />;
}
```

**Comment by Daviontheone** [comment]
Thanks @cwtuan this example will be very helpful for anyone that experiences this in the future

**Comment by Veveue** [comment]
Rewrite it to:
```js

// global variable
const constants = {
    fruits: [
      {
        get label() {
          return intl.get("banana");
        },
        value: "banana",
      },
      {
        get label() {
          return intl.get("apple");
        },
        value: "apple",
      },
    ],
  };
  function MyComponent() {
    // fruits is a function which returns message when rendering
    return <Select dataSource={constants.fruits} />;
  }
```

**Comment by Veveue** [comment]
> Yes, you should call `intl.init` before `render`.
> 
> For example, if you have some constants like this:
> 
> ```js
> // Wrong: the message in constants.fruits is used before `intl.init(...)`
> const constants = {
>     fruits : [
>         { label: intl.get('banana'), value: 'banana' },
>         { label: intl.get('apple'), value: 'apple' },
>     ]
> }
> function MyComponent() {
>     return <Select dataSource={constants.fruits} />
> }
> ```
> 
> Rewrite it to:
> 
> ```js
> // Correct: make the message as a function, and call it at render function
> const constants = {
>     fruits : () => [  // as arrow function
>         { label: intl.get('banana'), value: 'banana' },
>         { label: intl.get('apple'), value: 'apple' },
>     ]
> }
> function MyComponent() {
>     // fruits is a function which returns message when rendering
>     return <Select dataSource={constants.fruits()} />
> }
> ```

```js
// global variable
const constants = {
    fruits: [
      {
        get label() {
          return intl.get("banana");
        },
        value: "banana",
      },
      {
        get label() {
          return intl.get("apple");
        },
        value: "apple",
      },
    ],
  };
  function MyComponent() {
    // fruits is a function which returns message when rendering
    return <Select dataSource={constants.fruits} />;
  }
```

**Comment by cwtuan** [comment]
@Veveue  Yes, use [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) is better. Let me modify the example.

**Comment by cwtuan** [comment]
This issue's solution is documented in [FAQ](https://github.com/alibaba/react-intl-universal#faq) section.
