### ISSUE TITLE
plural form isn't incompatible for Android7.0? {key,plural,=1 {#st} =2 {#nd} =3 {#rd} other {#th}}

### ISSUE THREAD

**Issue by jiangkeyuan** [alibaba/react-intl-universal#147]
当 key 为 1,2,3 时正常显示,other 时 就显示 整行代码,是不是不兼容安卓7.0,  其余系统正常

**Comment by cwtuan** [comment]
your key is "1,2,3" ?

**Comment by jiangkeyuan** [comment]
code:{intl.get("2020.10.10",{nper:item.date})} date为 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15........
三语:2020.10.10:"hello {nper,plural,=1 {#nd} =2 {#rd} =3 {#rd} other [{#th}}"

**Comment by jiangkeyuan** [comment]
![微信图片_20201105142739](https://user-images.githubusercontent.com/40256761/98206332-afbd0580-1f74-11eb-8759-a2630de8976c.jpg)

**Comment by jiangkeyuan** [comment]
手机型号 :SHARP  FS8014  版本 安卓,7.0

**Comment by cwtuan** [comment]
Do you have the following code in your app? 

https://github.com/alibaba/react-intl-universal/blob/master/examples/node-js-example/src/App.js#L12-L16

**Comment by jiangkeyuan** [comment]
sure

**Comment by jiangkeyuan** [comment]
1,2,3 都正常显示了 other 这个api是不是不支持            只有安卓7.0 显示不正常  其余系统正常

**Comment by cwtuan** [comment]
any error message in console?

**Comment by jiangkeyuan** [comment]
good morning !

**Comment by jiangkeyuan** [comment]
- #
![WechatIMG324](https://user-images.githubusercontent.com/40256761/98317981-8ce42d00-2018-11eb-9f13-7ff50ca54eff.jpeg)
![WechatIMG325](https://user-images.githubusercontent.com/40256761/98317988-8f468700-2018-11eb-94d8-47fd12d39c9c.jpeg)

**Comment by jiangkeyuan** [comment]
"react-intl-universal": "^2.4.1",

**Comment by cwtuan** [comment]
Please try this,
```
npm i --save @formatjs/intl-pluralrules
```

```
import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en' // locale-data for en
```

**Comment by jiangkeyuan** [comment]
it is ok!  thanks
