### ISSUE TITLE
想问一下，determineLocale中提供的几种方式，都必须要刷新页面才能切换语言吗？fallbackLocale这种用法有没有示例，其他的几种方式尝试过了，要刷新页面才能渲染语言，有没有什么方式可以在不刷新页面的情况下就切换语言？

### ISSUE THREAD

**Issue by itwangyun** [alibaba/react-intl-universal#149]

**Comment by itwangyun** [comment]
自己处理了一下，在修改语言切换的函数里，重新使用了
![image](https://user-images.githubusercontent.com/38803819/99620721-0b04f280-2a61-11eb-927d-52cc6a932c04.png)

可以正常切换了。重点是 intl.init() 函数的使用。

**Comment by cwtuan** [comment]
1. Just set `fallbackLocale` in `intl.init() ` such as `intl.init({fallbackLocale:'en-US'})`
2. After language changed, `intl.init()` again
