### ISSUE TITLE
version 1.2.0 - npm run build - slowly！！！

### ISSUE THREAD

**Issue by lzsheng** [alibaba/react-intl-universal#15]
### 从1.1.1版本升级至1.2.0版本后
运行官方browser-example的代码，执行npm start是很快的，但是在执行npm run build的时候，大概要构建2-3分钟。

在我自己的项目中（使用v1.1.1版本，构建时间大概是45s），但是升级了v1.2.0后等待超过10分钟依然不能构建成功！！！但是换回 v1.1.1 版本后，却能正常构建

请尽快解决这个问题～～辛苦啦

**Comment by lzsheng** [comment]
运行官方的browser-example，把版本降为1.1.1，速度明显比v1.2.0快很多！

**Comment by cwtuan** [comment]
what's your node version and OS?

**Comment by cwtuan** [comment]
Building `browser-example` consumes about 140s in both of v1.1.1 and v1.2 in my computer (Mac air, node v6.11.0)

**Comment by lzsheng** [comment]
nonde:7.2.1
macOS:10.12.4 (mbp 2016)

**Comment by lzsheng** [comment]
v1.2.0: building browser-example consumes about 114s
v1.1.1: building browser-example consumes about 12s

**Comment by cwtuan** [comment]
Currently, you could use v1.1 if you only need browser rendering.
v1.2 supports server rendering.

**Comment by lzsheng** [comment]
ok,thx!

**Comment by Jorer** [comment]
There is a significant size difference in the builds between 1.1.1 and 1.2.0. 

My locale loading goes something like this:
```
import intl from 'react-intl-universal';
import fi from './locales/fi';
import en from './locales/en';

const locales = {
  'fi-FI': fi,
  'en-US': en,
}
const locale = 'en-US';

const loadLocales = () => {
  intl.init({
    currentLocale: locale,
    locales,
  }).then(() => {
    //console.log("locales loaded");
  });
}
```

Building the package:
v1.1.1: 
File sizes after gzip:
  156.54 KB  build/static/js/main.588b5386.js
  2.21 KB    build/static/css/main.aa3bb3e1.css

v1.2.0:
File sizes after gzip:
  1003.92 KB (+847.34 KB)  build/static/js/main.5580900c.js
  2.21 KB                  build/static/css/main.aa3bb3e1.css

Checked the build with source-map-explorer and it does include locale data files for every language, not just the ones defined with the locales.

**Comment by cwtuan** [comment]
reopen #15 still not fixed
