### ISSUE TITLE
出现了一个奇怪的警告

### ISSUE THREAD

**Issue by yfs-2000** [alibaba/react-intl-universal#150]
en.js 
`marketAnalysis:{
  tab: ["Products", "Analysis"],
}`
使用时
`
intl.get("marketAnalysis.tab")[this.props.marketAnalyticsActive]
`
this.props.marketAnalyticsActive为"0"或"1"
这时候控制台出现一个警告
`react-intl-universal format message failed for key='marketAnalysis.tab'. The intl string context variable "undefined" was not provided to the string "undefined"` 我不知道为什么会出现这个警告  使用似乎也是正常的  这个会有什么影响吗

**Comment by yfs-2000** [comment]
当尝试为`intl.get(`marketAnalysis.tab.${this.props.marketAnalyticsActive}`)` 时  警告消失

**Comment by cwtuan** [comment]
`intl.get` is supposed to return a string instead of a object.
