### ISSUE TITLE
vite创建的项目，用此插件会报错

### ISSUE THREAD

**Issue by xiaosenzhang** [alibaba/react-intl-universal#154]
vite创建的项目，用此插件会报错

**Comment by cwtuan** [comment]
please provide more message

**Comment by xiaosenzhang** [comment]
> please provide more message

用[vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)创建react项目   
在App.jsx中 import intl from 'react-intl-universal'  后
![image](https://user-images.githubusercontent.com/31362628/108318317-96c22280-71fa-11eb-81d6-d6c7e0d3fe94.png)
![image](https://user-images.githubusercontent.com/31362628/108318415-c2dda380-71fa-11eb-930a-a50f4cd02319.png)

**Comment by cheerylong** [comment]
> > please provide more message
> 
> 用[vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)创建react项目
> 在App.jsx中 import intl from 'react-intl-universal' 后
> ![image](https://user-images.githubusercontent.com/31362628/108318317-96c22280-71fa-11eb-81d6-d6c7e0d3fe94.png)
> ![image](https://user-images.githubusercontent.com/31362628/108318415-c2dda380-71fa-11eb-930a-a50f4cd02319.png)

请问解决了吗？也遇到了同样的问题

**Comment by xiaosenzhang** [comment]
> > > please provide more message
> > 
> > 
> > 用[vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)创建react项目
> > 在App.jsx中 import intl from 'react-intl-universal' 后
> > ![image](https://user-images.githubusercontent.com/31362628/108318317-96c22280-71fa-11eb-81d6-d6c7e0d3fe94.png)
> > ![image](https://user-images.githubusercontent.com/31362628/108318415-c2dda380-71fa-11eb-930a-a50f4cd02319.png)
> 
> 请问解决了吗？也遇到了同样的问题

我找到了两种解决方法：
1. 直接改node_modules中的源码，把global  换成 var
2. 
![image](https://user-images.githubusercontent.com/31362628/134803690-a33a825c-c4b1-4b62-aba2-913176859fa3.png)

**Comment by cheerylong** [comment]
我也是采用了window.global = window解决。

**Comment by cwtuan** [comment]
please use the last version react-intl-universal@2.10.1
