### ISSUE TITLE
format message failed for key='organization.columnDefs'. The intl string context variable "undefined" was not provided to the string "undefined"

### ISSUE THREAD

**Issue by Myhappyboy** [alibaba/react-intl-universal#162]
excuse me！when use react-intl-universal hint message，local data format organization ={ columnDefs: [{ headerName: 'rowNumber', field: 'rowNumber', minWidth: 70, pinned: 'left', hide: false, cellRenderer: "filter_rowNumber", lockPosition: true},{ headerName: 'name', field: 'name', hide: false, minWidth: 180},]}

**Comment by cwtuan** [comment]
Please provide more info. I couldn't understand your question.
