### ISSUE TITLE
react-intl-universal-extract not work for Chinese

### ISSUE THREAD

**Issue by hongdeyuan** [alibaba/react-intl-universal#165]
```
import intl from 'react-intl-universal';

export default function Custom404() {
  return <h1>{intl.get('没有找到该资源').defaultMessage('404 - 没有找到该资源')}</h1>;
}
```
//package.json
"intl:extract": "react-intl-universal-extract --cmd extract --source-path ./ --output-path ./lang/locales/zhCN.json --verbose",

In the zhCN.json file, the content cannot be extracted：` intl.get('没有找到该资源').defaultMessage('404 - 没有找到该资源')` 

so， I suspect  react-intl-universal-extract  does not support Chinese keys

**Comment by hongdeyuan** [comment]
`const DETECT_REGEXP = /(intl|IntlUtils)\s*\.\s*(get\s*\(\s*["'`]([\w\.-]+)["'`][\s\S]*?\)\s*\.\s*(defaultMessage|d)\s*\(\s*[`"']([\s\S]+?)[`"']|getHTML*\s*\(\s*["'`]([\w\.-]+)["'`][\s\S]*?\)\s*\.\s*(defaultMessage|d)\s*\(\s*(["'`<][\s\S]+?["'`>]))[\s*,]*\)/gm;`

Replace ： src/util/constant.js for **support Chinese keys**

`const DETECT_REGEXP = /(intl|IntlUtils)\s*\.\s*(get\s*\(\s*["'`]([\s\S]+?)["'`][\s\S]*?\)\s*\.\s*(defaultMessage|d)\s*\(\s*[`"']([\s\S]+?)[`"']|getHTML*\s*\(\s*["'`]([\s\S]+?)["'`][\s\S]*?\)\s*\.\s*(defaultMessage|d)\s*\(\s*(["'`<][\s\S]+?["'`>]))[\s*,]*\)/gm;`

**Comment by hongdeyuan** [comment]
PR： https://github.com/alibaba/react-intl-universal/pull/166

**Comment by cwtuan** [comment]
Yes, Chinese key isn't supported and not recommended.

**Comment by hongdeyuan** [comment]
why not recommended?

**Comment by cwtuan** [comment]
The json key is better to be English.
