### ISSUE TITLE
HTML inside a variable doesn't work

### ISSUE THREAD

**Issue by djonathas** [alibaba/react-intl-universal#168]
I realized today it is not possible to put HTML tags inside a variable, like that:

```
const items = ' <br />Item 1<br />Item 2';
const text = intl.getHTML('key', { items });
```

the result is:
`Test List <br />Item 1<br />Item 2`

**Comment by cwtuan** [comment]
Yes, the variable will be a string in the result.

In your case, you could separate them into two parts. 
```jsx
const items = ['Item1', 'Item2'];
return (
<div>
  {intl.get('key').d('Test List ')}
  {items.map(item=>(<><br />{item}</>))}
</div>
)
```

**Comment by djonathas** [comment]
Yes, I did this for now. But I thought it was good have this feature to variable too
