### ISSUE TITLE
Missing typings for ReactIntlUniversal class

### ISSUE THREAD

**Issue by Dario91** [alibaba/react-intl-universal#171]
Hi,
is there a reason why the ReactIntlUniversal class isn't exposed in the index.d.ts file?

**Comment by cwtuan** [comment]
It does. Check: https://github.com/alibaba/react-intl-universal/blob/master/packages/react-intl-universal/typings/index.d.ts
![image](https://user-images.githubusercontent.com/3455798/132085065-212c4925-853d-4391-80ac-64d8a6930ef4.png)
