### ISSUE TITLE
react-intl-universal-extract work wrong for some situation!!!

### ISSUE THREAD

**Issue by pumpkinduan** [alibaba/react-intl-universal#174]
### 操作流程与业务代码
1. 如下为编写的业务代码，在一个.tsx文件中：
```tsx
const radioConfig = [
   {
        title: intl.get('meet_room.room_booking.simple_repeat_type_never'),
        value: Type.never,
    },
    {
        title: intl.get('meet_room.room_booking.simple_repeat_type_daily'),
        value: Type.daily,
    },
    {
        title: intl.get('meet_room.room_booking.simple_repeat_type_workday').d('TEST'),
        value: Type.workday,
    },
    {
        title: intl.get('meet_room.room_booking.simple_repeat_type_weekly'),
        value: Type.weekly,
    },
    {
        title: intl.get('meet_room.room_booking.simple_repeat_type_monthly'),
        value: Type.monthly,
    },
    {
        title: intl.get('meet_room.room_booking.simple_repeat_type_custom').d('Custom'),
        value: Type.custom,
    },
];

const Component = () => {
      const header = useMemo(() => {
         return {
            title:  !isSelectedCustomMode()
                    ? intl.get('meet_room.room_booking.circle_tip')
                    : intl.get('meet_room.room_booking.simple_repeat_type_custom').d('Custom'),
            left:  <Icon type="Back" size={24} onClick={handleGoBack} />,
            right: (
                <TextButton type="primary" onClick={handleConfirm}>
                    {intl.get('common.button.ok')}
                </TextButton>
            ),
        };
    }, [handleConfirm, handleGoBack, isSelectedCustomMode])
}
```
2. 我需要提取key-value至json文件中，理想情况下是生成这样的json：
```json
{
    "meet_room.room_booking.simple_repeat_type_custom": "Custom",
    "meet_room.room_booking.simple_repeat_type_workday": "TEST"
}
```
3. 但由于不兼容intl.get('key')的写法，必须写intl.get('key').d('value')，脚本才会正常提取文案，原因是如下代码：
![image](https://user-images.githubusercontent.com/34852848/134836971-865e2d6e-0247-4793-b34a-afbcdb843a1d.png)
4. 所以为了兼容原来的写法：intl.get('key')，校验message没有默认值时的错误处理，我暂时关闭了, 且过滤掉了没有默认值的message，如下图：
![image](https://user-images.githubusercontent.com/34852848/134837691-8de2595f-b352-425a-89b7-57961e139975.png)

5. 然后 执行 react-intl-universal-extract --cmd extract --source-path ./src --output-path ./locales/cn.json
6. 最后生成出来的json文件，部分key值与value对应不上，如下：
```json
{
     "meet_room.room_booking.circle_tip": "Custom",
     "meet_room.room_booking.simple_repeat_type_never": "TEST",
     "meet_room.room_booking.simple_repeat_type_weekly": "Custom"
}
```

### 疑问？？？我打印了extractMessage执行时，正则匹配的结果，如下：
![image](https://user-images.githubusercontent.com/34852848/134838509-4c927471-e488-4bfa-8752-c5620c0cd6f1.png)

![image](https://user-images.githubusercontent.com/34852848/134838474-8cbc881a-2ac7-4c1c-92c7-f242c5ef5402.png)
我想，match[3]应该为'meet_room.room_booking.simple_repeat_type_workday'这个key才对，但实际却是‘meet_room.room_booking.simple_repeat_type_never’
**是这个匹配的正则出了问题，还是这个工具的机制是这样呢？**

**Comment by cwtuan** [comment]
All of the `.d` or `.defaultMessage` is required for extracting message.

**Comment by serfgy** [comment]
`intl.get('common.special').d('special')
`
are you saying the .d is compulsory for all .get()?

**Comment by cwtuan** [comment]
> `intl.get('common.special').d('special') ` are you saying the .d is compulsory for all .get()?

Yes, it is.
