### ISSUE TITLE
升级2.4.10后getHTML方法异常

### ISSUE THREAD

**Issue by ppxu** [alibaba/react-intl-universal#177]
从2.4.8升级到2.4.10后getHTML方法渲染异常，重现例子
https://codesandbox.io/s/react-intl-universal-example-forked-mz6ie?file=/package.json
改成2.4.8即正常

**Comment by berziiii** [comment]
Second this - upgrading to 2.4.10 breaks both getHTML and formatHTMLMessage - usage throws console error of INVALID_TAG

**Comment by cwtuan** [comment]
Thanks for the report.
Fixed in `react-intl-universal@2.4.11`.
