### ISSUE TITLE
Object.assign problem in android 4.4.2

### ISSUE THREAD

**Issue by lzsheng** [alibaba/react-intl-universal#18]
构建出来的lib包，并没有对 Object.assign 等进行转码，导致在android 4.4.2 版本的设备上，在执行 init 的时候报错（因为不支持Object.assign ）
现在我通过添加 babel-polyfill 垫片库，然后才能正常运行 react-intl-universal的init方法
希望在后续版本可以在打包的时候就加入类似Object.assign的兼容细节。麻烦了！

**Comment by cwtuan** [comment]
You can just include `//f.alicdn.com/es5-shim/4.5.7/es5-shim.min.js` and `http://f.alicdn.com/es6-shim/0.35.1/es6-shim.min.js` in your html to support older browser.

**Comment by hardfist** [comment]
> You can just include `//f.alicdn.com/es5-shim/4.5.7/es5-shim.min.js` and `http://f.alicdn.com/es6-shim/0.35.1/es6-shim.min.js` in your html to support older browser.

不应该依赖使用者去做polyfill吧，应该是库里使用core-js去做polyfill吧，否则没办法使用@babel/preset-env的useBuiltIns:'usage'特性了
