### ISSUE TITLE
Can the console-polyfill dependency be removed?

### ISSUE THREAD

**Issue by kaiyoma** [alibaba/react-intl-universal#182]
I'm running into a problem with a project that uses this package:

```
.../common/temp/node_modules/.pnpm/console-polyfill@0.3.0/node_modules/console-polyfill/index.js:13
  if (!global.console) {
              ^

TypeError: Cannot read properties of undefined (reading 'console')
```

Why does this package need `console-polyfill`? Browsers and Node both have a console, so the polyfill seems unnecessary. (I've never seen any other npm package use that dependency.) I cloned this project and manually removed that dependency and the build still works and I get the same pass rate for the unit tests. Can the console-polyfill dependency be removed?

**Comment by cwtuan** [comment]
fixed in `react-intl-universal@2.5.0`.
