### ISSUE TITLE
React18 is not supported

### ISSUE THREAD

**Issue by x93008** [alibaba/react-intl-universal#184]
➜  react-js git:(main) ✗ npm i react-intl-universal -S
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-js@1.0.7
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.0.0 || ^16.0.0 || ^17.0.0" from react-intl-universal@2.5.1
npm ERR! node_modules/react-intl-universal
npm ERR!   react-intl-universal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/x93008/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/x93008/.npm/_logs/2022-04-20T07_38_47_320Z-debug.log
➜   react-js git:(main) ✗

**Comment by x93008** [comment]
"dependencies": {
    "axios": "^0.26.1",
    "qrcode.react": "^3.0.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }

**Comment by cwtuan** [comment]
fixed in v2.5.3.
