### ISSUE TITLE
Mirror react-intl API

### ISSUE THREAD

**Issue by aeirola** [alibaba/react-intl-universal#2]
First, thanks for creating this package! I've been looking for something similar ever since I started using `react-intl`.

As the documentation suggests this package as an replacement to `react-intl`, it would be really nice if it would provide the same [API](https://github.com/yahoo/react-intl/wiki/API) as the injected `intl` object.

So instead of formatting a message with

```javascript
intl.get('SIMPLE')
```

it would use the same API as react-intl

```javascript
intl.formatMessage({id: 'SIMPLE'})
```

This would make it a lot easier for existing users of react-intl to transition to this package.

**Comment by cwtuan** [comment]
@aeirola That's good idea. I will implement it recently.
