### ISSUE TITLE
Support for nested JSON data?

### ISSUE THREAD

**Issue by dantzchan** [alibaba/react-intl-universal#20]
I am working on a big project, and there are a lot of pages.
I think it would be good to organize the locale data in json by nesting data.

```
"page1": {
  "first_sentence": "this is first sentence",
  "second_sentence": "this is second sentence" 
},
"page2": ...
```

**Comment by cwtuan** [comment]
How do you like to get translated  value? 
Something like `intl.get('page1.first_sentence')`?

**Comment by elgalesmana** [comment]
Any update for this 🤔

**Comment by cwtuan** [comment]
This feature is supported in v1.4.3. 
Check the [Release note](https://github.com/alibaba/react-intl-universal/releases/tag/1.4.3).
