### ISSUE TITLE
{days, plural, zero {# يوم} one {# يوم} two {# أيام} few {# أيام} many {# يوم} other {# يوم}} 这种应该怎么写

### ISSUE THREAD

**Issue by hjxtclm** [alibaba/react-intl-universal#217]
{days, plural, zero {# يوم} one {# يوم} two {# أيام} few {# أيام} many {# يوم} other {# يوم}} 这种应该怎么写。
只会命中other情况

**Comment by cwtuan** [comment]
https://github.com/alibaba/react-intl-universal#plural-form-and-number-thousands-separators
