### ISSUE TITLE
请问最新版本能完全兼容1.3.4版本吗？

### ISSUE THREAD

**Issue by fanxueqin** [alibaba/react-intl-universal#220]
以前项目里面固定使用1.3.4版本，因为1.3.4版本打包之后有语言文件导致体积比较大。现在想升级到最新版本(2.6.X) , 想问一下最新版能兼容1.3.4版本吗。项目中使用到以下4个API:
```
intl.get().d()
intl.getHTML().d()
intl.init({
  currentLocale: '',
  locales:{}
})
intl.options.currentLocale
```
thanks❤️

**Comment by cwtuan** [comment]
yes, it is. Upgrading to 2.x will decrease the bundle size.
