### ISSUE TITLE
Switch to another language

### ISSUE THREAD

**Issue by lany9527** [alibaba/react-intl-universal#23]
我最近按照你们提供的例子试了一下，在react组件里面定义全局变量，然后切换多语言发现不能够显示对应的语言：请问是不是不支持针对全局变量的多语言翻译。
代码简化如下：
` const title=`${intl.get('时间')}`；

 ` class Demo {
   render () {
      return (
        <h1>{title}</h1>
     )
   }
} `

在切换多语言的时候并不能够翻译title变量。求解

**Comment by cwtuan** [comment]
When switching to another language, you need to call `intl.init(..)` to set the `currentLocale`, and then force render the component (i.e., reload page or `component.forceUpdate()`).

Please refer to https://github.com/alibaba/react-intl-universal/blob/master/examples/browser-example/src/App.js#L77-L86
