### ISSUE TITLE
Typescript moduleResolution Bundler does not work properly in combination with strict true

### ISSUE THREAD

**Issue by NicoVogel** [alibaba/react-intl-universal#236]
Minimal Repo that reproduces the error: https://github.com/NicoVogel/react-intl-universal-module-resolution-bundler

This package does not work with the new `"moduleResolution": "Bundler"` configuration for Typescript in combination with `"strict": true`.
![image](https://github.com/alibaba/react-intl-universal/assets/19486965/29c05fb7-c9df-4e4c-9558-2acbb663dfac)

> Could not find a declaration file for module 'react-intl-universal'. '[...]/react-intl-universal-module-resolution-bundler/node_modules/react-intl-universal/es/index.js' implicitly has an 'any' type.
  There are types at '[...]/react-intl-universal-module-resolution-bundler/node_modules/react-intl-universal/typings/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-intl-universal' library may need to update its package.json or typings.

**Comment by cwtuan** [comment]
Released in react-intl-universal@2.8.0
