### ISSUE TITLE
请问 nexjs 怎么实现？ 急急急！

### ISSUE THREAD

**Issue by xian107** [alibaba/react-intl-universal#249]
react-intl-universal/examples /nextjs-example/ 这个例子是每个页面都要像index首页一样init()一次吗?
![image](https://github.com/alibaba/react-intl-universal/assets/13252682/dc89509c-387b-4794-9b59-b2e0c763dfcc)
而且加了initDone网页查看页面源代码的时候，并没有渲染出来翻译的文字和html
怎么才能在app.tsx页面设置

**Comment by cwtuan** [comment]
You could write something like Skeleton for all of your page.
