### ISSUE TITLE
How to use in  /public/index.html

### ISSUE THREAD

**Issue by lany9527** [alibaba/react-intl-universal#25]
hi:
How to use "react-intl-universal" in  /public/index.html to translate text in tag <title>some word</title>

**Comment by cwtuan** [comment]
You can change html title in frontend.
```js
document.title = intl.get('title');
```
Or render html in server side: https://github.com/alibaba/react-intl-universal/blob/master/examples/node-js-example/public/index.html

**Comment by sasaluo** [comment]
in which  page using document.title = intl.get('title');? i have the same problem
