### ISSUE TITLE
Typescript declaration file

### ISSUE THREAD

**Issue by rakeshmotghare** [alibaba/react-intl-universal#30]
Could you please provide a type definition file for this package. I am using typescript in my project and want to use this with the typescript.

**Comment by cwtuan** [comment]
@rakeshmotghare https://github.com/alibaba/react-intl-universal/releases/tag/1.8.0

**Comment by kuy** [comment]
@cwtuan Is there any reason still unpublished?

**Comment by cwtuan** [comment]
Please refer to https://github.com/alibaba/react-intl-universal/pull/42.

**Comment by cwtuan** [comment]
published in  v1.8.4.
