### ISSUE TITLE
The build is to big

### ISSUE THREAD

**Issue by iLeonelPerea** [alibaba/react-intl-universal#32]
Hi..

I am using this implementation and works perfectly. But the problem that after do the build is that the dependency intl (react-intl-universal) consume a lot of space, look the image.

intl imports all the languages (close to 20 mb) and i only need two. 

How I can limit the languages to require only the ones that I need.?

<img width="1574" alt="screen shot 2017-11-02 at 1 01 41 pm" src="https://user-images.githubusercontent.com/2968628/32344927-12b78fc0-bfce-11e7-8abb-9266a86d6ae3.png">

**Comment by cwtuan** [comment]
Do you use the latest version?
