### ISSUE TITLE
Load translations from S3 amazon

### ISSUE THREAD

**Issue by ClementLoridan** [alibaba/react-intl-universal#34]
How to init with json file hosting in S3 amazon for dynamic translations ? Thk

**Comment by cwtuan** [comment]
Please refer to https://github.com/alibaba/react-intl-universal/blob/master/examples/browser-example/src/App.js#L72-L88 for more detail about getting json file dynamically. If your file is hosting in S3, you could use jsonp instead.

**Comment by ClementLoridan** [comment]
Thk, and it will work in server side rendering ?

**Comment by cwtuan** [comment]
react-intl-universal supports SSR. Please refer to https://github.com/alibaba/react-intl-universal/tree/master/examples/node-js-example.
