### ISSUE TITLE
How to get Locale-data without using cdn

### ISSUE THREAD

**Issue by liuzhuonan** [alibaba/react-intl-universal#43]
我们的项目不能不能使用外网，有没有什么办法把我想要的几种语言的locale-data放在本地进行访问。
  SYS_LOCALE_DATA_URL是不是加个容错比较好，如果无法访问那个网站则采用另一种方式

**Comment by cwtuan** [comment]
Currently, you can write a script to scan your built file, and save external files to local disk.

**Comment by liuzhuonan** [comment]
Thanks, I think I know how to do it.
