### ISSUE TITLE
https://g.alicdn.com/react-intl-universal/locale-data/1.0.0/zh.js

### ISSUE THREAD

**Issue by Mrxdh** [alibaba/react-intl-universal#50]
我用了react-intl-universal 在发布完代码以后，总会自己加载这个js文件包，我想问一下这个js文件重要吗，可不可以有办法不加载？

**Comment by cwtuan** [comment]
It's used for formatting date, num, currency, and etc.

**Comment by cwtuan** [comment]
@Mrxdh 我们在招聘前端开发，有兴趣吗

**Comment by raunyuyuan** [comment]
we have been this plugIn, But the promise get rejected and the error is 

```
Failed to load https://g.alicdn.com/react-intl-universal/locale-data/1.0.0/zh.js In ie environment
```

**Comment by cwtuan** [comment]
@raunyuyuan  Which IE version?

**Comment by raunyuyuan** [comment]
@cwtuan  Had resolved this problem just download two files zh.js and en.js in my project, then write following code:

```
intl.init({
                  currentLocale,
                  locales: {
                      [currentLocale]: data
                  },
                  commonLocaleDataUrls: {
                    en: "/static/langlib/en.js", // the file
                    zh: "/static/langlib/zh.js" // the file
                  }
              });
```
the param commonLocaleDataUrls is used to translate language? could you share some url?thanks :）

**Comment by cwtuan** [comment]
`https://g.alicdn.com/react-intl-universal/locale-data/1.0.0/en.js`

**Comment by dragonge** [comment]
请问内网环境请求不通这个地址怎么办？

**Comment by cwtuan** [comment]
@dragonge 

Upgrade to  the latest version which will not load CND resource.
