### ISSUE TITLE
documentation or at least a list of API functions

### ISSUE THREAD

**Issue by musichen** [alibaba/react-intl-universal#55]
Hello guys, 
    was experimenting with your library 'react-intl-universal'  recently. 
I feel totally blind in terms of documentation, there is not enough info in repo description. 

@cwtuan could you please add at least a list of all functions available in API of 'react-intl-universal' ?

Or if you need any help writing one, i would like to help, in this case, @cwtuan please pm me
alex.musichen@gmail.com

Thank you in advance!

**Comment by cwtuan** [comment]
API list is in README.
