### ISSUE TITLE
How to use the react-intl-universal lib in electron without network?

### ISSUE THREAD

**Issue by lizaminelli** [alibaba/react-intl-universal#56]
1. In my project, I use electron, react, antd and react-intl-universal.
2. In electron, the typeof window !== "undefined", so the isBrowser is true.
3. If the the isBrowser is true, will add CDN locale data, but my app may be used without network.
so , is there a way to solve this problem?

**Comment by cwtuan** [comment]
How do I check if the environment is electron? Any suggestion?
