### ISSUE TITLE
如何能够动态切换当前的语言？

### ISSUE THREAD

**Issue by Gpia** [alibaba/react-intl-universal#60]

**Comment by wuyechang** [comment]
重新调用一遍init(options)方法就行了吧

**Comment by Gpia** [comment]
我使用了切换语言，将语言记录在cookie中，然后刷新页面的方式。每次页面加载会从cookie读取，然后初始化一次。也就是切换语言必然刷新页面，这样也能避免很多问题，如动态切换后，当前的所有组件需要触发一次重绘，会有多余的业务代码。反而刷新页面是最简单有效的一种方式。

**Comment by wuzinong** [comment]
@wuyechang  您好，我试了下init方法，是可以切换语言，但是当前页面的语言不会改变，要切到别的页面在切回来才有效果，我是在router里面做的，请问有什么好的方法吗？谢谢

**Comment by cwtuan** [comment]
@wuzinong forceUpdate after locale changed
