### ISSUE TITLE
能否让用户可以手动设置CLDR文件的CDN路径？

### ISSUE THREAD

**Issue by wuyechang** [alibaba/react-intl-universal#63]
现在的CLDR文件的CDN下载路径是直接硬编码的。这样一来就有这么几个问题：
1、有时候g.alicdn.com会非常慢，需要5秒钟以上才能完成文件下载，严重影响用户体验；
2、我们项目希望所有的相关文件都配置在自己的CDN服务器上；
3、很多客户的公司使用proxy来访问外部网络，未必会允许访问g.alicdn.com（我们的客户主要在海外，对于他们来说g.alicdn.com是非常陌生的）；
4、虽然可以手动修改src/index.js来解决上述问题，但是因为是硬编码，所以不得不将库文件直接复制到项目的repository里来修改，用自己的git来管理这个库的源代码，感觉很糟……

**Comment by Gpia** [comment]
我也是这样的。我的专有云环境，都是物理隔离的，不能访问cdn

**Comment by cwtuan** [comment]
Released in https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0.
