### ISSUE TITLE
COMMON_LOCALE_DATA_URLS - why not included in the package?

### ISSUE THREAD

**Issue by arturgieralt** [alibaba/react-intl-universal#68]
Hi All,

First of all, thanks for the very good lib.
Could you tell me why that data is hosted on CDN, not included in the lib itself?
My app wastes about 1sec to get it from CDN, I would appreciate an option to host it by myself.

What do you think about that? What's the reason of keeping these on external servers?

Regards,
Artur

**Comment by cwtuan** [comment]
where are you located? 
It should not be so slow for CDN.
The locale data will be cached after first load.

**Comment by arturgieralt** [comment]
Poland - I have 300Mbps download speed. 
I'm trying to tweak up performance of my site. Here are some stats:
- when not cached:
first meaningful paint: 1000ms
scripting of en.js starts on 800ms and ends 1500ms (700ms of scripting in one file)
last rerender is around 1900ms

- when cached:
first meaningful paint: 700ms
- last rerender around 800ms

I use antD library which gets fonts from CDN, this lib does the same. I'd like to cut down the timings. 

Is it possible (in the future) to inject COMMON_LOCALE_DATA_URLS as an option to init function? There is @options param, any chance to extend it?

Thank you,
Artur

**Comment by arturgieralt** [comment]
I've forked to your project, changed routes in the package, indeed your CDN is very fast. Scripting takes less time when file is hosted on my server, but downloading is not the issue. You can close and sorry for the troubles. On the other hand, I still think its nice to have feature to override these links.

Cheers,
Thanks for the good work!

**Comment by cwtuan** [comment]
Ok, I will take it into consideration.

**Comment by cwtuan** [comment]
Released in https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0.
