### ISSUE TITLE
默认的语言包是从alicdn加载的，这个是否可以设置？？？

### ISSUE THREAD

**Issue by Gpia** [alibaba/react-intl-universal#71]
因为我的产品部署环境是专有云环境，不能访问alicdn环境。所以我希望这个语言包的地址是可以配置的。我可以配置成网站本身的文件，或者使用json导入

**Comment by ringcrazy** [comment]
intl源码中有语言包，可以引用，不过得copy一份react-intl-universal/lib/index.js的文件，手动修改COMMON_LOCALE_DATA_URLS路径，暂时想到的方法，还没有找到如何配置的方法

**Comment by cwtuan** [comment]
Released in https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0.
