### ISSUE TITLE
Make loading of common locale optional

### ISSUE THREAD

**Issue by MikeMcElroy** [alibaba/react-intl-universal#76]
It shouldn't be required that the package go out to a third-party CDN.  It'd be nice to be able to specify the `COMMON_LOCALE_DATA_URLS` or be able to bundle an entire locale package in with the initialization.  Something like:
```js
intl.init({
  currentLocale: 'en-US',
  locales: {
    'en-US': { ... }
  },
  localeUrls: {
    'en-US': 'https://nonexistentUrl.cdn.com/localedata/en-us.json'
  },
  localeData: {
    'en-US': { ... }
  }
})
```

**Comment by cwtuan** [comment]
Released in https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0.
