### ISSUE TITLE
Edge 浏览器报错：failed to load zh.js

### ISSUE THREAD

**Issue by ndaybreak** [alibaba/react-intl-universal#77]
![image](https://user-images.githubusercontent.com/9065444/44833352-6a983d00-ac60-11e8-8682-3c9d1493e3c3.png)

**Comment by cwtuan** [comment]
@ndaybreak 
Does it work in https://g.alicdn.com/alishu/common/0.0.95/intl-example/index.html ?

**Comment by ndaybreak** [comment]
yes it works fine.
My project is deployed in localhost, maybe it is the reason.

**Comment by cwtuan** [comment]
OK. I close it.
