### ISSUE TITLE
Remove network dependency for downloading polyfills

### ISSUE THREAD

**Issue by jhaenchen** [alibaba/react-intl-universal#84]
I'm building a progressive web app that sometimes is offline and refreshes. In those scenarios, react-intl-universal causes a network exception to be shown in the console as the request initiated [here](https://github.com/alibaba/react-intl-universal/blob/master/src/index.js#L194) fails. I recommend we move these files to the repository and you can have your build/deployment process copy these files as they're updated. There's no need for this repo to reach out to the internet.

**Comment by cwtuan** [comment]
You could download the common locale data to your build directory in your build script.
Then set `commonLocaleDataUrls ` to local path.
https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0

**Comment by jhaenchen** [comment]
@cwtuan Thanks!

**Comment by jhaenchen** [comment]
@cwtuan What if I'm not using the currency or date formatting functions? I'd like to just remove these locale files altogether until I need them, but if I pass an empty array as `commonLocaleDataUrls` I get the error saying `language is not supported`.

**Comment by cwtuan** [comment]
Shouldn't pass an empty array. Just pass the local path of common locale data in your app.

**Comment by OZZlE** [comment]
> Shouldn't pass an empty array. Just pass the local path of common locale data in your app.

Can you explain how to do this for, for example React:

I downloaded: `https://g.alicdn.com/react-intl-universal/locale-data/1.0.0/en.js` then I saved it in a local folder as `localeCache.js` and did:

    import localeCache from 'locales/localeCache';
    intl.init({
    currentLocale: localeHack,
        locales: LocaleHelper.getLocales(),
        commonLocaleDataUrls: localeCache,
    })

Still shows "index.js:266 Language "en" is not supported. Check https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0"

But all the local translations still works.. but I don't like the warning in console.

**Comment by cwtuan** [comment]
@OZZlE 
Could you log `localeCache`?

**Comment by OZZlE** [comment]
this is strange.. I did the same steps again and now it works fine :S so nevermind :P

**Comment by OZZlE** [comment]
Ok so it "works" but it still logs a warning "index.js:266 Language "en" is not supported." and then it breaks in IE11 + Edge <= v.16

**Comment by jlpatrick** [comment]
We have been seeing intermittent long delays when fetching https://g.alicdn.com/react-intl-universal/locale-data/1.0.0/en.js that prevent our product from loading while waiting, so have been forced to switch to a `commonLocaleDataUrls` override solution. It would be nice to remove the network dependency as originally requested.

**Comment by cwtuan** [comment]
@jhaenchen 
You can host the files  to your server by overriding `commonLocaleDataUrls` currently.
We may consider remove the network dependency by default in next major release.

**Comment by jhaenchen** [comment]
It's not me bringing the ticket up again, but anyone who is using `commonLocaleDataUrls` override will need to not let webpack transform the import into a JSON object. The internal code expects a URL to GET. I'm not sure what loader will need to be disabled and I don't know how you would disable loading JSON for only that single import since in most cases you want JSON as the object.

It might be valuable to let `commonLocaleDataUrls` accept a JSON object as well. That would make using the override easier.

**Comment by cwtuan** [comment]
Fixed in https://github.com/alibaba/react-intl-universal/releases/tag/2.0.3

`commonLocaleDataUrls` is deprecated. And you could `require` the locale data in your app.
