### ISSUE TITLE
getHTML returns double quotes for <a href

### ISSUE THREAD

**Issue by yairzaslavsky** [alibaba/react-intl-universal#86]
I tried to use getHTML with a text containing <a href="www.mywebsite.com">click </a>
and this returned me an <a> tag which looked like this:

<a href=""www.mywebsite.com"">click </a>

**Comment by cwtuan** [comment]
@yairzaslavsky 
Show me the code and locale data.

**Comment by cwtuan** [comment]
Closing this issue because of no response.
