### ISSUE TITLE
Format currency options

### ISSUE THREAD

**Issue by nicolasrouanne** [alibaba/react-intl-universal#87]
It would be nice to have a way to **_format currencies_ according to certain options**, such as _decimal point_. This might be a good implementation for _numbers_ as well.

Something like what `react-intl` [is providing](https://github.com/yahoo/react-intl/wiki/Components#formattednumber).

**Comment by cwtuan** [comment]
[Thousands separators](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html) are displayed properly according to the currency code. Users doesn't need to set it manual.

**Comment by nicolasrouanne** [comment]
I don't want to select the _thousand separator_ to display, rather the _precision_ of a displayed number

```js
intl.get("PRICE", { amount: 1000 })
```

```json
"PRICE": "{amount, number, EUR}"
```

This would display `€ 1,000.00` in  `en-US` for instance. 
I would like to display `€ 1,000`.

**Comment by cwtuan** [comment]
Could you show me your `init` function?

**Comment by nicolasrouanne** [comment]
How is the `init` function related to being able to choose the number of decimal of a number?
Here is the one I use in my mocks:
```js
import enUS from "../public/locales/en-US.json";

intl.init({
  warningHandler: () => {},
  currentLocale: "en-US",
  locales: { "en-US": enUS }
});
```

I had some _afterthought_: maybe what I'm looking for is **a wrapper** around [`Number.prototype.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString). 

Anyway in the meantime , I switched to `.toLocaleString()` for number formatting, passing it the locale defined in `react-intl-universal`

```js
const Price = ({ amount }) => {
  const { currentLocale } = intl.getInitOptions();
  return (
    amount && (
      <span className="price">
        {amount.toLocaleString(currentLocale, {
          style: "currency",
          currency: "EUR",
          minimumFractionDigits: 0,
          maximumFractionDigits: 0
        })}
      </span>
    )
  );
};
```

**Comment by cwtuan** [comment]
Yes, you could use `Number.prototype.toLocaleString()` instead if the default formatting isn't suitable in your case.
