### ISSUE TITLE
Printing JSX / React Element Usage

### ISSUE THREAD

**Issue by ls-endurance** [alibaba/react-intl-universal#88]
Problem Description:
In our organization, we're trying to use either the intl.get() or intl.getHTML() api in order to render react elements in conjunction with the message strings.

[See a gist that demonstrates the issue here](https://gist.github.com/ls-endurance/a3db5c00edfd28a82cd73c15e4465680)

I searched old issues, and no one posted this up.

I imagine that we would need to run through the message and each variable needs to be create an element that requires it to be set 'dangerously'.

Are there any plans to add this feature? (This feature already exists with React-Intl from Yahoo.)

**Comment by cwtuan** [comment]
In your gist, 
```
            intl.getHTML('connectClick', { 
              icon: <div>This does not work.</div>
            })
```

The second parameter is a variable object instead of default message. 

Use `.d` for the default message.
```
intl.getHTML('connectClick').d({ <span> icon: <div>This does not work.</div> </span> }))
```

**Comment by ls-endurance** [comment]
You're right, it is a variable object - a React element. That was on purpose.

I am saying that the library does not support this feature.

Here is react-intl supporting elements as variables: 
![image](https://user-images.githubusercontent.com/40364466/47660926-162d1300-db66-11e8-8e67-9373859f832d.png)

Here's the link: https://github.com/yahoo/react-intl/wiki/Components#rich-text-formatting
